name: Build TAF-EB Portátil

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2025

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependências
        run: npm install

      - name: Gerar TAF-EB-Portatil.exe
        run: npx electron-builder --win portable --x64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar executável
        uses: actions/upload-artifact@v4
        with:
          name: TAF-EB-Portatil
          path: dist/TAF-EB-Portatil.exe
          retention-days: 90
